#!/bin/bash
####################################################################
### delta=1e-3
####################################################################

###################################################################
## mesh-independent for the validating example,  tol = 5.e-8, kappa = 5e-5, sin10
###################################################################
## unstructured-mesh
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 75 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7300 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27300_mesh_idp_sin10_resolution75_delta_1e3.txt
#
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 80 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7301 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27301_mesh_idp_sin10_resolution80_delta_1e3.txt
#
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 85 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7302 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27302_mesh_idp_sin10_resolution85_delta_1e3.txt
#
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 90 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7303 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27303_mesh_idp_sin10_resolution90_delta_1e3.txt
#
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 95 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7304 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27304_mesh_idp_sin10_resolution95_delta_1e3.txt
#
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 100 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7305 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27305_mesh_idp_sin10_resolution100_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 105 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7306 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27306_mesh_idp_sin10_resolution105_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 110 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7307 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27307_mesh_idp_sin10_resolution110_delta_1e3.txt

# structured mesh
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.01 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7310 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27310_mesh_idp_sin10_h_1e_2_delta_1e3.txt
#
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.009 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7311 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27311_mesh_idp_sin11_h_9e_3_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.008 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7312 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27312_mesh_idp_sin10_h_8e_3_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.007 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7313 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27313_mesh_idp_sin10_h_7e_3_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.006 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7314 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27314_mesh_idp_sin10_h_6e_3_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7315 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27315_mesh_idp_sin10_h_5e_3_delta_1e3.txt


###################################################################
## mesh-independent for the validating example,  tol = 5.e-8, kappa = 5e-5, sin8
###################################################################
## unstructured-mesh
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 8 --problem.initial_guess.sin_py 8 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 75 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7320 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27320_mesh_idp_sin8_resolution75_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 8 --problem.initial_guess.sin_py 8 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 80 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7321 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27321_mesh_idp_sin8_resolution80_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 8 --problem.initial_guess.sin_py 8 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 85 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7322 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27322_mesh_idp_sin8_resolution85_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 8 --problem.initial_guess.sin_py 8 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 90 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7323 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27323_mesh_idp_sin8_resolution90_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 8 --problem.initial_guess.sin_py 8 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 95 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7324 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27324_mesh_idp_sin8_resolution95_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 8 --problem.initial_guess.sin_py 8 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 100 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7325 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27325_mesh_idp_sin8_resolution100_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 8 --problem.initial_guess.sin_py 8 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 105 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7326 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27326_mesh_idp_sin8_resolution105_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 8 --problem.initial_guess.sin_py 8 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 110 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7327 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27327_mesh_idp_sin8_resolution110_delta_1e3.txt

# structured mesh
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 8 --problem.initial_guess.sin_py 8 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.01 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7330 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27330_mesh_idp_sin8_h_1e_2_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 8 --problem.initial_guess.sin_py 8 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.009 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7331 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27331_mesh_idp_sin8_h_9e_3_delta_1e3.txt
#
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 8 --problem.initial_guess.sin_py 8 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.008 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7332 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27332_mesh_idp_sin8_h_8e_3_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 8 --problem.initial_guess.sin_py 8 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.007 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7333 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27333_mesh_idp_sin8_h_7e_3_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 8 --problem.initial_guess.sin_py 8 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.006 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7334 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27334_mesh_idp_sin8_h_6e_3_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 8 --problem.initial_guess.sin_py 8 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7335 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27335_mesh_idp_sin8_h_5e_3_delta_1e3.txt

###################################################################
## mesh-independent for the validating example,  tol = 5.e-8, kappa = 5e-5, sin2
###################################################################
## unstructured-mesh
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 2 --problem.initial_guess.sin_py 2 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 75 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7340 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27340_mesh_idp_sin2_resolution75_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 2 --problem.initial_guess.sin_py 2 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 80 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7341 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27341_mesh_idp_sin2_resolution80_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 2 --problem.initial_guess.sin_py 2 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 85 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7342 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27342_mesh_idp_sin2_resolution85_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 2 --problem.initial_guess.sin_py 2 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 90 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7343 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27343_mesh_idp_sin2_resolution90_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 2 --problem.initial_guess.sin_py 2 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 95 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7344 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27344_mesh_idp_sin2_resolution95_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 2 --problem.initial_guess.sin_py 2 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 100 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7345 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27345_mesh_idp_sin2_resolution100_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 2 --problem.initial_guess.sin_py 2 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 105 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7346 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27346_mesh_idp_sin2_resolution105_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 2 --problem.initial_guess.sin_py 2 --problem.const.delta 1.e-3 --mesh.structured_mesh 0 --mesh.resolution 110 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7347 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27347_mesh_idp_sin2_resolution110_delta_1e3.txt

## structured mesh
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 2 --problem.initial_guess.sin_py 2 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.01 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7350 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27350_mesh_idp_sin2_h_1e2_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 2 --problem.initial_guess.sin_py 2 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.009 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7351 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27351_mesh_idp_sin2_h_9e_3_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 2 --problem.initial_guess.sin_py 2 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.008 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7352 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27352_mesh_idp_sin2_h_8e_3_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 2 --problem.initial_guess.sin_py 2 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.007 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7353 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27353_mesh_idp_sin2_h_7e_3_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 2 --problem.initial_guess.sin_py 2 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.006 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7354 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27354_mesh_idp_sin2_h_6e_3_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 2 --problem.initial_guess.sin_py 2 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.resolution 110 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7355 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27355_mesh_idp_sin2_h_5e_3_delta_1e3.txt
