#!/bin/bash
####################################################################
### delta=1e-3
####################################################################
####################################################################
### influence of eta ex2, tol = 5e-6
####################################################################
mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7510 --problem.const.eta 0.1 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27510_eta10_delta_1e3.txt


mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7509 --problem.const.eta 0.09 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27509_eta09_delta_1e3.txt

mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7508 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27508_eta08_delta_1e3.txt

##Ex27507 did not converged with tol 5e-8
mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7507 --problem.const.eta 0.07 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27507_eta07_delta_1e3.txt

mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7506 --problem.const.eta 0.06 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27506_eta06_delta_1e3.txt

mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7505 --problem.const.eta 0.05 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27505_eta05_delta_1e3.txt

mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7504 --problem.const.eta 0.04 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27504_eta04_delta_1e3.txt

mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7503 --problem.const.eta 0.03 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27503_eta03_delta_1e3.txt

mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7502 --problem.const.eta 0.02 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27502_eta02_delta_1e3.txt

mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-5 --ex 2 --problem.case 7501 --problem.const.eta 0.01 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27501_eta01_delta_1e3.txt
