#!/bin/bash
####################################################################
### delta=1e-3
####################################################################
###################################################################
## initial guess and local optimal solutions
###################################################################
# 27600 did not converge, all others converged
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5e-8 --solver_alpha.gradient_relative_tol 5e-8 --solver_alpha.gradient_t_tol 5e-8 --problem.initial_guess.is_constant 1 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --ex 2 --problem.case 7600 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 --problem.const.kappa 5.e-5 post_processing.TAO_saving_frequency 200|& tee -a ex27600_initial_guess_alpha0_1_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5e-8 --solver_alpha.gradient_relative_tol 5e-8 --solver_alpha.gradient_t_tol 5e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 2 --problem.initial_guess.sin_py 2 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --ex 2 --problem.case 7601 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 --problem.const.kappa 5.e-5 post_processing.TAO_saving_frequency 200|& tee -a ex27601_initial_guess_alpha0_sin2_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5e-8 --solver_alpha.gradient_relative_tol 5e-8 --solver_alpha.gradient_t_tol 5e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 4 --problem.initial_guess.sin_py 4 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --ex 2 --problem.case 7602 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 --problem.const.kappa 5.e-5 post_processing.TAO_saving_frequency 200|& tee -a ex27602_initial_guess_alpha0_sin6_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5e-8 --solver_alpha.gradient_relative_tol 5e-8 --solver_alpha.gradient_t_tol 5e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 6 --problem.initial_guess.sin_py 6 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --ex 2 --problem.case 7603 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 --problem.const.kappa 5.e-5 post_processing.TAO_saving_frequency 200|& tee -a ex27603_initial_guess_alpha0_sin8_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5e-8 --solver_alpha.gradient_relative_tol 5e-8 --solver_alpha.gradient_t_tol 5e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 8 --problem.initial_guess.sin_py 8 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --ex 2 --problem.case 7604 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 --problem.const.kappa 5.e-5 post_processing.TAO_saving_frequency 200|& tee -a ex27604_initial_guess_alpha0_sin10_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5e-8 --solver_alpha.gradient_relative_tol 5e-8 --solver_alpha.gradient_t_tol 5e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --ex 2 --problem.case 7605 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 --problem.const.kappa 5.e-5 post_processing.TAO_saving_frequency 200|& tee -a ex27605_initial_guess_alpha0_sin10_delta_1e3.txt
