#!/bin/bash
####################################################################
### delta=1e-3
####################################################################
#####################################################################
#### influence of kappa ex2, tol = 5e-8
#####################################################################
#exex27400 converged
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 1.e-15 --ex 2 --problem.case 7400 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27400_kappa_1e_15_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 1.e-6 --ex 2 --problem.case 7401 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27401_kappa_1e_6_delta_1e3.txt

#exex27402 converged
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 5.e-6 --ex 2 --problem.case 7402 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27402_kappa_5e_6_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 1.e-5 --ex 2 --problem.case 7403 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27403_kappa_1e_5_delta_1e3.txt

#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 2.e-5 --ex 2 --problem.case 7404 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27404_kappa_2e_5_delta_1e3.txt
#
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 4.e-5 --ex 2 --problem.case 7405 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27405_kappa_4e_5_delta_1e3.txt
#
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 6.e-5 --ex 2 --problem.case 7406 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27406_kappa_6e_5_delta_1e3.txt
#
#exex27407 converged
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 8.e-5 --ex 2 --problem.case 7407 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27407_kappa_8e_5_delta_1e3.txt

##exex27408 converged
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 1.e-4 --ex 2 --problem.case 7408 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27408_kappa_1e_4_delta_1e3.txt
#
#exex27409 converged
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 2.e-4 --ex 2 --problem.case 7409 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27409_kappa_2e_4_delta_1e3.txt
#
#exex27410 converged
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 4.e-4 --ex 2 --problem.case 7410 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27410_kappa_4e_4_delta_1e3.txt
#
#exex27411 converged
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 6.e-4 --ex 2 --problem.case 7411 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27411_kappa_6e_4_delta_1e3.txt
#
#exex27412 converged
#mpirun -np 8 python3 AS_phase_field_opt.py --solver_alpha.gradient_absolute_tol 5.e-8 --solver_alpha.gradient_relative_tol 5.e-8 --solver_alpha.gradient_t_tol 5.e-8 --problem.initial_guess.is_constant 0 --problem.initial_guess.sin_px 10 --problem.initial_guess.sin_py 10 --problem.const.delta 1.e-3 --mesh.structured_mesh 1 --mesh.cell_size 0.005 --material.ell 0.025 --problem.const.kappa 8.e-4 --ex 2 --problem.case 7412 --problem.const.eta 0.08 --problem.force.gy -1 --problem.obstacle.ub_u_y 1.e8 --problem.obstacle.lb_u_y -0.02 post_processing.TAO_saving_frequency 200|& tee -a ex27412_kappa_8e_4_delta_1e3.txt

